version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
    networks:
      - phalcon-network

networks:
  phalcon-network:
    driver: bridge
